import { TypeScriptMongoosePluginConfig } from './config'
import { TsMongooseAbstractGenerator } from './generators/abstractGenerator'
import { TsMongooseSchemaGenerator } from './generators/schemaGenerator'
import { TsMongooseDAOGenerator } from './generators/daoGenerator'

export type TsMongooseGeneratorField = {
  name: string
  type: string | { embed?: string; innerRef?: string; foreignRef?: string; refFrom?: string; refTo?: string }
  mongooseType: string
  required: boolean
  isID: boolean
  isAutogenerated: boolean
  isList: boolean
  isExcluded: boolean
}

export type TsMongooseGeneratorNode = {
  type?: string
  code: string
  name: string
  prefixedName: string
  isEntity: boolean
  collection: string
  interfaces: string[]
  fields: TsMongooseGeneratorField[]
}

export class TsMongooseGenerator {
  private _generators: TsMongooseAbstractGenerator[]

  constructor(config: TypeScriptMongoosePluginConfig) {
    this._generators = [new TsMongooseSchemaGenerator(config), new TsMongooseDAOGenerator(config)]
  }

  public generate(nodes: TsMongooseGeneratorNode[]): string {
    const typesMap = new Map<string, TsMongooseGeneratorNode>()
    nodes.filter((node) => node.type === 'type').forEach((type) => typesMap.set(type.code, type))

    this.checkIds(typesMap)
    this.checkReferences(typesMap)

    const imports = this._generators
      .map((generator) => {
        return generator.generateImports()
      })
      .reduce((a, c) => [...a, ...c], [])

    const definitions = nodes
      .filter((node) => node.type)
      .flatMap((node) => {
        const definition = this._generators
          .map((generator) => generator.generateDefinition(node, typesMap))
          .filter((definition) => definition !== '')
          .join('\n\n')
        if (definition.trim().length === 0) {
          return []
        } else {
          return [[this._generateTitle(node), definition].join('\n\n')]
        }
      })

    const exports = this._generators.map((generator) => generator.generateExports(typesMap))

    return [imports.join('\n'), definitions.join('\n\n\n\n'), exports.join('\n\n')].join('\n\n')
  }

  private _generateTitle(node: TsMongooseGeneratorNode): string {
    return (
      '//' +
      '-'.repeat(80) +
      '\n' +
      '//' +
      '-'.repeat((80 - node.name.length - ((node.name.length % 2) + 1)) / 2) +
      ' ' +
      node.name.toUpperCase() +
      ' ' +
      '-'.repeat((80 - node.name.length - 1) / 2) +
      '\n' +
      '//' +
      '-'.repeat(80)
    )
  }

  private checkIds(typesMap: Map<String, TsMongooseGeneratorNode>) {
    Array.from(typesMap.values())
      .filter((type) => type.isEntity)
      .forEach((type) => {
        const id = this._findID(type)
        if (!id) {
          throw new Error(`Type ${type.name} requires an @id field being a @mongoEntity.`)
        }
      })
  }

  private checkReferences(typesMap: Map<String, TsMongooseGeneratorNode>) {
    Array.from(typesMap.values()).forEach((type) => {
      type.fields.forEach((field) => {
        if (typeof field.type !== 'string') {
          if (field.type.innerRef) {
            const refType = this._findNode(field.type.innerRef, typesMap)
            if (!refType) {
              throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.innerRef} that cannot be resolved.`)
            }
            if (!refType.isEntity) {
              throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.innerRef} that isn't a mongoEntity.`)
            }
            if (field.type.refFrom) {
              const refFromField = this._findField(type, field.type.refFrom, typesMap)
              if (!refFromField) {
                throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.innerRef} with refFrom ${field.type.refFrom} that cannot be resolved.`)
              }
            }
            if (field.type.refTo) {
              const refToField = this._findField(refType, field.type.refTo, typesMap)
              if (!refToField) {
                throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.innerRef} with refTo ${field.type.refTo} that cannot be resolved.`)
              }
            }
          } else if (field.type.foreignRef) {
            const refType = this._findNode(field.type.foreignRef, typesMap)
            if (!refType) {
              throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.foreignRef} that cannot be resolved.`)
            }
            if (field.type.refFrom) {
              const refFromField = this._findField(refType, field.type.refFrom, typesMap)
              if (!refFromField) {
                throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.foreignRef} with refFrom ${field.type.refFrom} that cannot be resolved.`)
              }
            }
            if (field.type.refTo) {
              const refToField = this._findField(type, field.type.refTo, typesMap)
              if (!refToField) {
                throw new Error(`Field ${field.name} of type ${type.name} has a reference to ${field.type.foreignRef} with refTo ${field.type.refTo} that cannot be resolved.`)
              }
            }
          }
        }
      })
    })
  }

  protected _findID(node: TsMongooseGeneratorNode): TsMongooseGeneratorField | undefined {
    return node.fields.find((field) => field.isID)
  }

  protected _findNode(code: string, typesMap: Map<String, TsMongooseGeneratorNode>): TsMongooseGeneratorNode | undefined {
    return typesMap.get(code)
  }

  protected _findField(node: TsMongooseGeneratorNode, fieldPath: string, typesMap: Map<String, TsMongooseGeneratorNode>): TsMongooseGeneratorField | undefined {
    const fieldPathSplitted = fieldPath.split('.')
    if (fieldPathSplitted.length === 1) {
      return node.fields.find((f) => f.name === fieldPathSplitted[0])
    } else {
      const key = fieldPathSplitted.shift()
      const tmpField = node.fields.find((f) => f.name === key)
      if (tmpField && typeof tmpField.type !== 'string' && tmpField.type.embed) {
        const embeddedType = this._findNode(tmpField.type.embed, typesMap)
        return embeddedType && this._findField(embeddedType, fieldPathSplitted.join('.'), typesMap)
      }
      return tmpField
    }
  }
}
