import { DAOParams } from '../../../dao/dao.types'
import { Projection } from '../../../dao/projections/projections.types'
import { Collection } from 'mongodb'

export type MongoDBDAOParams<
  ModelType,
  IDKey extends keyof Omit<ModelType, ExcludedFields>,
  IDType,
  IDAutogenerated extends boolean,
  FilterType,
  ProjectionType extends Projection<ModelType>,
  UpdateType,
  ExcludedFields extends keyof ModelType,
  SortType,
  OptionsType,
  ScalarsType,
> = DAOParams<ModelType, IDKey, IDType, IDAutogenerated, FilterType, ProjectionType, UpdateType, ExcludedFields, SortType, OptionsType, ScalarsType> & {
  collection: Collection
}
