import { DAOParams } from '../../../dao/dao.types'
import { Knex } from 'knex'
import { DefaultModelScalars } from '../../drivers.types'

export type KnexJsDAOParams<
  ModelType extends object,
  IDKey extends keyof Omit<ModelType, ExcludedFields>,
  IDType,
  IDAutogenerated extends boolean,
  FilterType,
  ProjectionType extends object,
  UpdateType,
  ExcludedFields extends keyof ModelType,
  SortType,
  OptionsType,
  ScalarsType extends DefaultModelScalars,
  > = Omit<
    DAOParams<ModelType, IDKey, IDType, IDAutogenerated, FilterType, ProjectionType, UpdateType, ExcludedFields, SortType, OptionsType, { knex: Knex }, ScalarsType>,
    'driverOptions'
  > & {
    tableName: string
    knex: Knex<any, unknown[]>
  }
