import { DAOParams, FindParams, FindOneParams, FilterParams, InsertParams, UpdateParams, ReplaceParams, DeleteParams } from '../../../dao/dao.types'
import { PartialDeep } from 'type-fest'
import { AbstractDAOContext } from '../../../daoContext/daoContext'
import { AbstractDAO } from '../../../dao/dao'
import { GenericProjection, Projection } from '../../../dao/projections/projections.types'
import knex, { Knex } from 'knex'
import { ComparisonOperators, ElementOperators, EvaluationOperators } from '../../../dao/filters/filters.types'
import { AbstractSort, buildSelect, buildSort, buildWhereConditions } from './utils'
import { transformObject } from '../../../../generation/utils'
import { Schema } from '../../../dao/schemas/schemas.types'

type AbstractFilter = {
  [key: string]: any | null | ComparisonOperators<any> | ElementOperators<any> | EvaluationOperators<any>
}

export abstract class AbstractMongooseDAO<
  ModelType extends object,
  IDKey extends keyof Omit<ModelType, ExcludedFields>,
  IDAutogenerated extends boolean,
  FilterType extends AbstractFilter,
  SortType,
  UpdateType,
  ExcludedFields extends keyof ModelType,
  OptionsType extends { knex?: any },
> extends AbstractDAO<ModelType, IDKey, IDAutogenerated, FilterType, SortType, UpdateType, ExcludedFields, OptionsType> {
  private schema: Schema<any>
  private collectionName: string
  private knex: Knex<any, unknown[]>

  protected constructor({
    collectionName,
    schema,
    knexConfig,
    ...params
  }: { idField: IDKey; daoContext: AbstractDAOContext; collectionName: string; schema: Schema<any>; knexConfig: Knex.Config } & DAOParams<
    ModelType,
    IDKey,
    IDAutogenerated,
    FilterType,
    UpdateType,
    ExcludedFields,
    SortType,
    OptionsType
  >) {
    super(params)
    this.schema = schema
    this.collectionName = collectionName
    this.knex = knex(knexConfig)
  }

  private qb(): Knex.QueryBuilder<any, any> {
    return this.knex(this.collectionName)
  }

  private dbToModel(objects: PartialDeep<ModelType>[]): PartialDeep<ModelType>[] {
    return objects.map((obj) => transformObject<PartialDeep<ModelType>, any>(this.daoContext.adapters, 'dbToModel', obj as PartialDeep<ModelType>, this.schema, this.daoContext.adapters.get('JSON')))
  }

  private modelToDb<T>(object: T): T {
    return transformObject<T, any>(this.daoContext.adapters, 'modelToDB', object, this.schema, this.daoContext.adapters.get('JSON'))
  }

  private buildSelect(projection?: Projection<ModelType>, qb?: Knex.QueryBuilder<any, any>): Knex.QueryBuilder<any, any> {
    return projection ? buildSelect(qb || this.qb(), projection as GenericProjection) : qb || this.qb()
  }

  private buildWhere(filter?: FilterType, qb?: Knex.QueryBuilder<any, any>): Knex.QueryBuilder<any, any> {
    return filter ? buildWhereConditions(qb || this.qb(), filter as AbstractFilter, this.schema, this.daoContext.adapters) : qb || this.qb()
  }

  private async getRecords(params: FindParams<FilterType, Projection<ModelType>, SortType, OptionsType>): Promise<PartialDeep<ModelType>[]> {
    const select = this.buildSelect(params.projection)
    const where = this.buildWhere(params.filter, select)
    const query = buildSort(where, (params.sorts || []) as AbstractSort[])
    const records = await query.limit(params.limit || this.pageSize).offset(params.start || 0)
    return this.dbToModel(records)
  }

  protected async _find(params: FindParams<FilterType, Projection<ModelType>, SortType, OptionsType>): Promise<PartialDeep<ModelType>[]> {
    return this.getRecords(params)
  }

  protected async _findOne(params: FindOneParams<FilterType, Projection<ModelType>, OptionsType>): Promise<PartialDeep<ModelType> | null> {
    const select = this.buildSelect(params.projection)
    const where = this.buildWhere(params.filter, select)
    const record = await where.first()
    return record ? record : null
  }

  protected async _findPage(params: FindParams<FilterType, Projection<ModelType>, SortType, OptionsType>): Promise<{ totalCount: number; records: PartialDeep<ModelType>[] }> {
    const totalCount = await this._count({ ...params })
    if (totalCount === 0) {
      return { totalCount, records: [] }
    }
    const records = await this.getRecords(params)
    return { totalCount, records }
  }

  protected async _exists(params: FilterParams<FilterType, OptionsType>): Promise<boolean> {
    return (await this._count(params)) > 0
  }

  protected async _count(params: FilterParams<FilterType, OptionsType>): Promise<number> {
    const count = this.qb().count(this.idField, { as: 'all' })
    const where = this.buildWhere(params.filter, count)
    const result = await where
    return result[0]['all'] as number
  }

  protected async _insertOne(params: InsertParams<ModelType, IDKey, ExcludedFields, IDAutogenerated, OptionsType>): Promise<Omit<ModelType, ExcludedFields>> {
    const insertObject = this.modelToDb(params.record)
    const records = await this.qb().insert(insertObject, '*')
    const inserted = records[0]
    if (typeof inserted === 'number') {
      //.returning() is not supported
      return { ...params.record } as Omit<ModelType, ExcludedFields>
    }
    return this.dbToModel(records)[0] as Omit<ModelType, ExcludedFields>
  }

  protected _updateOne(params: UpdateParams<FilterType, UpdateType, OptionsType>): Promise<void> {
    throw new Error(`Operation not supported. Use updateAll or apiV1.updateMany specifying the primary key field (${this.idField}) in order to update only one row.`)
  }

  protected async _updateMany(params: UpdateParams<FilterType, UpdateType, OptionsType>): Promise<void> {
    const updateObject = this.modelToDb(params.changes)
    const update = this.qb().update(updateObject)
    const where = this.buildWhere(params.filter, update)
    await where
  }

  protected _replaceOne(params: ReplaceParams<FilterType, ModelType, ExcludedFields, OptionsType>): Promise<void> {
    throw new Error(`Operation not supported.`)
  }

  protected _deleteOne(params: DeleteParams<FilterType, OptionsType>): Promise<void> {
    throw new Error(`Operation not supported. Use deleteAll or apiV1.delete specifying the primary key field (${this.idField}) in order to delete only one row.`)
  }

  protected async _deleteMany(params: DeleteParams<FilterType, OptionsType>): Promise<void> {
    const deleteQ = this.qb().delete()
    const where = this.buildWhere(params.filter, deleteQ)
    await where
  }
}
