import { Projection } from '../projections/projections.types'
import { DAOMiddleware } from './middlewares.types'

export function generateId<
  ModelType,
  IDKey extends keyof Omit<ModelType, ExcludedFields>,
  IDType,
  IDAutogenerated extends boolean,
  FilterType,
  ProjectionType extends Projection<ModelType>,
  UpdateType,
  ExcludedFields extends keyof ModelType,
  SortType,
  OptionsType,
  ScalarsType,
>(args: { generator?: () => IDType }): DAOMiddleware<ModelType, IDKey, IDAutogenerated, FilterType, ProjectionType, UpdateType, ExcludedFields, SortType, OptionsType, ScalarsType> {
  return {
    beforeInsert: async (params, context) => {
      if (!(context.idField in params.record)) {
        if (!args.generator) {
          throw new Error('ID generator is undefined.')
        }
        return { ...params, record: { ...params.record, [context.idField]: args.generator() } }
      }
      return params
    },
  }
}
