import { RawConfig, ScalarsMap } from '@graphql-codegen/visitor-plugin-common'
export interface TypeScriptMongoosePluginConfig extends RawConfig {
  /**
   * @name tsTypesImport
   * @type string
   * @default ./types
   * @description Customize the import of Typescript types generated with @graphql-codegen/typescript.
   *
   */
  tsTypesImport?: string
  /**
   * @name objectIdType
   * @type string
   * @default mongodb#ObjectId
   * @description Customize the type of `_id` fields.
   *
   */
  objectIdType?: string
  /**
   * @name idFieldName
   * @type string
   * @default _id
   * @description Customize the name of the id field generated after using `@id` directive over a GraphQL field.
   *
   */
  defaultIdAutogenerated?: boolean
  /**
   * @name mongooseScalars
   * @type ScalarsMap
   * @description Extends or overrides the built-in scalars and custom GraphQL scalars to a custom type for mongoose Schema definition.
   *
   */
  mongooseScalars?: ScalarsMap
}

export enum Directives {
  ID = 'id',
  ENTITY = 'mongoEntity',
  EMBEDDED = 'mongoEmbedded',
  INNER_REF = 'mongoInnerRef',
  FOREIGN_REF = 'mongoForeignRef',
  EXCLUDE = 'mongoExclude',
}
